Raycasting.DrawObject.XORFillColumn0:
	lda Raycast.ObjectDraw.Column0.w
	eor Raycast.ObjectDraw.Column0.w+1
	sta Raycast.ObjectDraw.Column0.w+1
	eor Raycast.ObjectDraw.Column0.w+2
	sta Raycast.ObjectDraw.Column0.w+2
	eor Raycast.ObjectDraw.Column0.w+3
	sta Raycast.ObjectDraw.Column0.w+3
	eor Raycast.ObjectDraw.Column0.w+4
	sta Raycast.ObjectDraw.Column0.w+4
	eor Raycast.ObjectDraw.Column0.w+5
	sta Raycast.ObjectDraw.Column0.w+5
	eor Raycast.ObjectDraw.Column0.w+6
	sta Raycast.ObjectDraw.Column0.w+6
	eor Raycast.ObjectDraw.Column0.w+7
	sta Raycast.ObjectDraw.Column0.w+7
	eor Raycast.ObjectDraw.Column0.w+8
	sta Raycast.ObjectDraw.Column0.w+8
	eor Raycast.ObjectDraw.Column0.w+9
	sta Raycast.ObjectDraw.Column0.w+9
	eor Raycast.ObjectDraw.Column0.w+10
	sta Raycast.ObjectDraw.Column0.w+10
	eor Raycast.ObjectDraw.Column0.w+11
	sta Raycast.ObjectDraw.Column0.w+11
	eor Raycast.ObjectDraw.Column0.w+12
	sta Raycast.ObjectDraw.Column0.w+12
	eor Raycast.ObjectDraw.Column0.w+13
	sta Raycast.ObjectDraw.Column0.w+13
	eor Raycast.ObjectDraw.Column0.w+14
	sta Raycast.ObjectDraw.Column0.w+14
	eor Raycast.ObjectDraw.Column0.w+15
	sta Raycast.ObjectDraw.Column0.w+15
	eor Raycast.ObjectDraw.Column0.w+16
	sta Raycast.ObjectDraw.Column0.w+16
	eor Raycast.ObjectDraw.Column0.w+17
	sta Raycast.ObjectDraw.Column0.w+17
	eor Raycast.ObjectDraw.Column0.w+18
	sta Raycast.ObjectDraw.Column0.w+18
	eor Raycast.ObjectDraw.Column0.w+19
	sta Raycast.ObjectDraw.Column0.w+19
	eor Raycast.ObjectDraw.Column0.w+20
	sta Raycast.ObjectDraw.Column0.w+20
	eor Raycast.ObjectDraw.Column0.w+21
	sta Raycast.ObjectDraw.Column0.w+21
	eor Raycast.ObjectDraw.Column0.w+22
	sta Raycast.ObjectDraw.Column0.w+22
	eor Raycast.ObjectDraw.Column0.w+23
	sta Raycast.ObjectDraw.Column0.w+23
	eor Raycast.ObjectDraw.Column0.w+24
	sta Raycast.ObjectDraw.Column0.w+24
	eor Raycast.ObjectDraw.Column0.w+25
	sta Raycast.ObjectDraw.Column0.w+25
	eor Raycast.ObjectDraw.Column0.w+26
	sta Raycast.ObjectDraw.Column0.w+26
	eor Raycast.ObjectDraw.Column0.w+27
	sta Raycast.ObjectDraw.Column0.w+27
	eor Raycast.ObjectDraw.Column0.w+28
	sta Raycast.ObjectDraw.Column0.w+28
	eor Raycast.ObjectDraw.Column0.w+29
	sta Raycast.ObjectDraw.Column0.w+29
	eor Raycast.ObjectDraw.Column0.w+30
	sta Raycast.ObjectDraw.Column0.w+30
	eor Raycast.ObjectDraw.Column0.w+31
	sta Raycast.ObjectDraw.Column0.w+31
	eor Raycast.ObjectDraw.Column0.w+32
	sta Raycast.ObjectDraw.Column0.w+32
	eor Raycast.ObjectDraw.Column0.w+33
	sta Raycast.ObjectDraw.Column0.w+33
	eor Raycast.ObjectDraw.Column0.w+34
	sta Raycast.ObjectDraw.Column0.w+34
	eor Raycast.ObjectDraw.Column0.w+35
	sta Raycast.ObjectDraw.Column0.w+35
	eor Raycast.ObjectDraw.Column0.w+36
	sta Raycast.ObjectDraw.Column0.w+36
	eor Raycast.ObjectDraw.Column0.w+37
	sta Raycast.ObjectDraw.Column0.w+37
	eor Raycast.ObjectDraw.Column0.w+38
	sta Raycast.ObjectDraw.Column0.w+38
	eor Raycast.ObjectDraw.Column0.w+39
	sta Raycast.ObjectDraw.Column0.w+39
	eor Raycast.ObjectDraw.Column0.w+40
	sta Raycast.ObjectDraw.Column0.w+40
	eor Raycast.ObjectDraw.Column0.w+41
	sta Raycast.ObjectDraw.Column0.w+41
	eor Raycast.ObjectDraw.Column0.w+42
	sta Raycast.ObjectDraw.Column0.w+42
	eor Raycast.ObjectDraw.Column0.w+43
	sta Raycast.ObjectDraw.Column0.w+43
	rts
	
Raycasting.DrawObject.XORFillColumn1:
	lda Raycast.ObjectDraw.Column1.w
	eor Raycast.ObjectDraw.Column1.w+1
	sta Raycast.ObjectDraw.Column1.w+1
	eor Raycast.ObjectDraw.Column1.w+2
	sta Raycast.ObjectDraw.Column1.w+2
	eor Raycast.ObjectDraw.Column1.w+3
	sta Raycast.ObjectDraw.Column1.w+3
	eor Raycast.ObjectDraw.Column1.w+4
	sta Raycast.ObjectDraw.Column1.w+4
	eor Raycast.ObjectDraw.Column1.w+5
	sta Raycast.ObjectDraw.Column1.w+5
	eor Raycast.ObjectDraw.Column1.w+6
	sta Raycast.ObjectDraw.Column1.w+6
	eor Raycast.ObjectDraw.Column1.w+7
	sta Raycast.ObjectDraw.Column1.w+7
	eor Raycast.ObjectDraw.Column1.w+8
	sta Raycast.ObjectDraw.Column1.w+8
	eor Raycast.ObjectDraw.Column1.w+9
	sta Raycast.ObjectDraw.Column1.w+9
	eor Raycast.ObjectDraw.Column1.w+10
	sta Raycast.ObjectDraw.Column1.w+10
	eor Raycast.ObjectDraw.Column1.w+11
	sta Raycast.ObjectDraw.Column1.w+11
	eor Raycast.ObjectDraw.Column1.w+12
	sta Raycast.ObjectDraw.Column1.w+12
	eor Raycast.ObjectDraw.Column1.w+13
	sta Raycast.ObjectDraw.Column1.w+13
	eor Raycast.ObjectDraw.Column1.w+14
	sta Raycast.ObjectDraw.Column1.w+14
	eor Raycast.ObjectDraw.Column1.w+15
	sta Raycast.ObjectDraw.Column1.w+15
	eor Raycast.ObjectDraw.Column1.w+16
	sta Raycast.ObjectDraw.Column1.w+16
	eor Raycast.ObjectDraw.Column1.w+17
	sta Raycast.ObjectDraw.Column1.w+17
	eor Raycast.ObjectDraw.Column1.w+18
	sta Raycast.ObjectDraw.Column1.w+18
	eor Raycast.ObjectDraw.Column1.w+19
	sta Raycast.ObjectDraw.Column1.w+19
	eor Raycast.ObjectDraw.Column1.w+20
	sta Raycast.ObjectDraw.Column1.w+20
	eor Raycast.ObjectDraw.Column1.w+21
	sta Raycast.ObjectDraw.Column1.w+21
	eor Raycast.ObjectDraw.Column1.w+22
	sta Raycast.ObjectDraw.Column1.w+22
	eor Raycast.ObjectDraw.Column1.w+23
	sta Raycast.ObjectDraw.Column1.w+23
	eor Raycast.ObjectDraw.Column1.w+24
	sta Raycast.ObjectDraw.Column1.w+24
	eor Raycast.ObjectDraw.Column1.w+25
	sta Raycast.ObjectDraw.Column1.w+25
	eor Raycast.ObjectDraw.Column1.w+26
	sta Raycast.ObjectDraw.Column1.w+26
	eor Raycast.ObjectDraw.Column1.w+27
	sta Raycast.ObjectDraw.Column1.w+27
	eor Raycast.ObjectDraw.Column1.w+28
	sta Raycast.ObjectDraw.Column1.w+28
	eor Raycast.ObjectDraw.Column1.w+29
	sta Raycast.ObjectDraw.Column1.w+29
	eor Raycast.ObjectDraw.Column1.w+30
	sta Raycast.ObjectDraw.Column1.w+30
	eor Raycast.ObjectDraw.Column1.w+31
	sta Raycast.ObjectDraw.Column1.w+31
	eor Raycast.ObjectDraw.Column1.w+32
	sta Raycast.ObjectDraw.Column1.w+32
	eor Raycast.ObjectDraw.Column1.w+33
	sta Raycast.ObjectDraw.Column1.w+33
	eor Raycast.ObjectDraw.Column1.w+34
	sta Raycast.ObjectDraw.Column1.w+34
	eor Raycast.ObjectDraw.Column1.w+35
	sta Raycast.ObjectDraw.Column1.w+35
	eor Raycast.ObjectDraw.Column1.w+36
	sta Raycast.ObjectDraw.Column1.w+36
	eor Raycast.ObjectDraw.Column1.w+37
	sta Raycast.ObjectDraw.Column1.w+37
	eor Raycast.ObjectDraw.Column1.w+38
	sta Raycast.ObjectDraw.Column1.w+38
	eor Raycast.ObjectDraw.Column1.w+39
	sta Raycast.ObjectDraw.Column1.w+39
	eor Raycast.ObjectDraw.Column1.w+40
	sta Raycast.ObjectDraw.Column1.w+40
	eor Raycast.ObjectDraw.Column1.w+41
	sta Raycast.ObjectDraw.Column1.w+41
	eor Raycast.ObjectDraw.Column1.w+42
	sta Raycast.ObjectDraw.Column1.w+42
	eor Raycast.ObjectDraw.Column1.w+43
	sta Raycast.ObjectDraw.Column1.w+43
	rts

Raycasting.DrawObject.XORFillColor0:
	lda #$FF
	eor Raycast.ObjectDraw.Color0.w
	sta Raycast.ObjectDraw.Color0.w
	eor Raycast.ObjectDraw.Color0.w+1
	sta Raycast.ObjectDraw.Color0.w+1
	eor Raycast.ObjectDraw.Color0.w+2
	sta Raycast.ObjectDraw.Color0.w+2
	eor Raycast.ObjectDraw.Color0.w+3
	sta Raycast.ObjectDraw.Color0.w+3
	eor Raycast.ObjectDraw.Color0.w+4
	sta Raycast.ObjectDraw.Color0.w+4
	eor Raycast.ObjectDraw.Color0.w+5
	sta Raycast.ObjectDraw.Color0.w+5
	eor Raycast.ObjectDraw.Color0.w+6
	sta Raycast.ObjectDraw.Color0.w+6
	eor Raycast.ObjectDraw.Color0.w+7
	sta Raycast.ObjectDraw.Color0.w+7
	eor Raycast.ObjectDraw.Color0.w+8
	sta Raycast.ObjectDraw.Color0.w+8
	eor Raycast.ObjectDraw.Color0.w+9
	sta Raycast.ObjectDraw.Color0.w+9
	eor Raycast.ObjectDraw.Color0.w+10
	sta Raycast.ObjectDraw.Color0.w+10
	eor Raycast.ObjectDraw.Color0.w+11
	sta Raycast.ObjectDraw.Color0.w+11
	eor Raycast.ObjectDraw.Color0.w+12
	sta Raycast.ObjectDraw.Color0.w+12
	eor Raycast.ObjectDraw.Color0.w+13
	sta Raycast.ObjectDraw.Color0.w+13
	eor Raycast.ObjectDraw.Color0.w+14
	sta Raycast.ObjectDraw.Color0.w+14
	eor Raycast.ObjectDraw.Color0.w+15
	sta Raycast.ObjectDraw.Color0.w+15
	eor Raycast.ObjectDraw.Color0.w+16
	sta Raycast.ObjectDraw.Color0.w+16
	eor Raycast.ObjectDraw.Color0.w+17
	sta Raycast.ObjectDraw.Color0.w+17
	eor Raycast.ObjectDraw.Color0.w+18
	sta Raycast.ObjectDraw.Color0.w+18
	eor Raycast.ObjectDraw.Color0.w+19
	sta Raycast.ObjectDraw.Color0.w+19
	eor Raycast.ObjectDraw.Color0.w+20
	sta Raycast.ObjectDraw.Color0.w+20
	eor Raycast.ObjectDraw.Color0.w+21
	sta Raycast.ObjectDraw.Color0.w+21
	eor Raycast.ObjectDraw.Color0.w+22
	sta Raycast.ObjectDraw.Color0.w+22
	eor Raycast.ObjectDraw.Color0.w+23
	sta Raycast.ObjectDraw.Color0.w+23
	eor Raycast.ObjectDraw.Color0.w+24
	sta Raycast.ObjectDraw.Color0.w+24
	eor Raycast.ObjectDraw.Color0.w+25
	sta Raycast.ObjectDraw.Color0.w+25
	eor Raycast.ObjectDraw.Color0.w+26
	sta Raycast.ObjectDraw.Color0.w+26
	eor Raycast.ObjectDraw.Color0.w+27
	sta Raycast.ObjectDraw.Color0.w+27
	eor Raycast.ObjectDraw.Color0.w+28
	sta Raycast.ObjectDraw.Color0.w+28
	eor Raycast.ObjectDraw.Color0.w+29
	sta Raycast.ObjectDraw.Color0.w+29
	eor Raycast.ObjectDraw.Color0.w+30
	sta Raycast.ObjectDraw.Color0.w+30
	eor Raycast.ObjectDraw.Color0.w+31
	sta Raycast.ObjectDraw.Color0.w+31
	eor Raycast.ObjectDraw.Color0.w+32
	sta Raycast.ObjectDraw.Color0.w+32
	eor Raycast.ObjectDraw.Color0.w+33
	sta Raycast.ObjectDraw.Color0.w+33
	eor Raycast.ObjectDraw.Color0.w+34
	sta Raycast.ObjectDraw.Color0.w+34
	eor Raycast.ObjectDraw.Color0.w+35
	sta Raycast.ObjectDraw.Color0.w+35
	eor Raycast.ObjectDraw.Color0.w+36
	sta Raycast.ObjectDraw.Color0.w+36
	eor Raycast.ObjectDraw.Color0.w+37
	sta Raycast.ObjectDraw.Color0.w+37
	eor Raycast.ObjectDraw.Color0.w+38
	sta Raycast.ObjectDraw.Color0.w+38
	eor Raycast.ObjectDraw.Color0.w+39
	sta Raycast.ObjectDraw.Color0.w+39
	eor Raycast.ObjectDraw.Color0.w+40
	sta Raycast.ObjectDraw.Color0.w+40
	eor Raycast.ObjectDraw.Color0.w+41
	sta Raycast.ObjectDraw.Color0.w+41
	eor Raycast.ObjectDraw.Color0.w+42
	sta Raycast.ObjectDraw.Color0.w+42
	eor Raycast.ObjectDraw.Color0.w+43
	sta Raycast.ObjectDraw.Color0.w+43
	rts
	
Raycasting.DrawObject.ClearColumnArrays:
	lda #$00
	sta Raycast.ObjectDraw.Column0.w+0
	sta Raycast.ObjectDraw.Column0.w+1
	sta Raycast.ObjectDraw.Column0.w+2
	sta Raycast.ObjectDraw.Column0.w+3
	sta Raycast.ObjectDraw.Column0.w+4
	sta Raycast.ObjectDraw.Column0.w+5
	sta Raycast.ObjectDraw.Column0.w+6
	sta Raycast.ObjectDraw.Column0.w+7
	sta Raycast.ObjectDraw.Column0.w+8
	sta Raycast.ObjectDraw.Column0.w+9
	sta Raycast.ObjectDraw.Column0.w+10
	sta Raycast.ObjectDraw.Column0.w+11
	sta Raycast.ObjectDraw.Column0.w+12
	sta Raycast.ObjectDraw.Column0.w+13
	sta Raycast.ObjectDraw.Column0.w+14
	sta Raycast.ObjectDraw.Column0.w+15
	sta Raycast.ObjectDraw.Column0.w+16
	sta Raycast.ObjectDraw.Column0.w+17
	sta Raycast.ObjectDraw.Column0.w+18
	sta Raycast.ObjectDraw.Column0.w+19
	sta Raycast.ObjectDraw.Column0.w+20
	sta Raycast.ObjectDraw.Column0.w+21
	sta Raycast.ObjectDraw.Column0.w+22
	sta Raycast.ObjectDraw.Column0.w+23
	sta Raycast.ObjectDraw.Column0.w+24
	sta Raycast.ObjectDraw.Column0.w+25
	sta Raycast.ObjectDraw.Column0.w+26
	sta Raycast.ObjectDraw.Column0.w+27
	sta Raycast.ObjectDraw.Column0.w+28
	sta Raycast.ObjectDraw.Column0.w+29
	sta Raycast.ObjectDraw.Column0.w+30
	sta Raycast.ObjectDraw.Column0.w+31
	sta Raycast.ObjectDraw.Column0.w+32
	sta Raycast.ObjectDraw.Column0.w+33
	sta Raycast.ObjectDraw.Column0.w+34
	sta Raycast.ObjectDraw.Column0.w+35
	sta Raycast.ObjectDraw.Column0.w+36
	sta Raycast.ObjectDraw.Column0.w+37
	sta Raycast.ObjectDraw.Column0.w+38
	sta Raycast.ObjectDraw.Column0.w+39
	sta Raycast.ObjectDraw.Column0.w+40
	sta Raycast.ObjectDraw.Column0.w+41
	sta Raycast.ObjectDraw.Column0.w+42
	sta Raycast.ObjectDraw.Column0.w+43
	sta Raycast.ObjectDraw.Column0.w+44
	sta Raycast.ObjectDraw.Column1.w+0
	sta Raycast.ObjectDraw.Column1.w+1
	sta Raycast.ObjectDraw.Column1.w+2
	sta Raycast.ObjectDraw.Column1.w+3
	sta Raycast.ObjectDraw.Column1.w+4
	sta Raycast.ObjectDraw.Column1.w+5
	sta Raycast.ObjectDraw.Column1.w+6
	sta Raycast.ObjectDraw.Column1.w+7
	sta Raycast.ObjectDraw.Column1.w+8
	sta Raycast.ObjectDraw.Column1.w+9
	sta Raycast.ObjectDraw.Column1.w+10
	sta Raycast.ObjectDraw.Column1.w+11
	sta Raycast.ObjectDraw.Column1.w+12
	sta Raycast.ObjectDraw.Column1.w+13
	sta Raycast.ObjectDraw.Column1.w+14
	sta Raycast.ObjectDraw.Column1.w+15
	sta Raycast.ObjectDraw.Column1.w+16
	sta Raycast.ObjectDraw.Column1.w+17
	sta Raycast.ObjectDraw.Column1.w+18
	sta Raycast.ObjectDraw.Column1.w+19
	sta Raycast.ObjectDraw.Column1.w+20
	sta Raycast.ObjectDraw.Column1.w+21
	sta Raycast.ObjectDraw.Column1.w+22
	sta Raycast.ObjectDraw.Column1.w+23
	sta Raycast.ObjectDraw.Column1.w+24
	sta Raycast.ObjectDraw.Column1.w+25
	sta Raycast.ObjectDraw.Column1.w+26
	sta Raycast.ObjectDraw.Column1.w+27
	sta Raycast.ObjectDraw.Column1.w+28
	sta Raycast.ObjectDraw.Column1.w+29
	sta Raycast.ObjectDraw.Column1.w+30
	sta Raycast.ObjectDraw.Column1.w+31
	sta Raycast.ObjectDraw.Column1.w+32
	sta Raycast.ObjectDraw.Column1.w+33
	sta Raycast.ObjectDraw.Column1.w+34
	sta Raycast.ObjectDraw.Column1.w+35
	sta Raycast.ObjectDraw.Column1.w+36
	sta Raycast.ObjectDraw.Column1.w+37
	sta Raycast.ObjectDraw.Column1.w+38
	sta Raycast.ObjectDraw.Column1.w+39
	sta Raycast.ObjectDraw.Column1.w+40
	sta Raycast.ObjectDraw.Column1.w+41
	sta Raycast.ObjectDraw.Column1.w+42
	sta Raycast.ObjectDraw.Column1.w+43
	sta Raycast.ObjectDraw.Column0.w+44
	sta Raycast.ObjectDraw.Color0.w+0
	sta Raycast.ObjectDraw.Color0.w+1
	sta Raycast.ObjectDraw.Color0.w+2
	sta Raycast.ObjectDraw.Color0.w+3
	sta Raycast.ObjectDraw.Color0.w+4
	sta Raycast.ObjectDraw.Color0.w+5
	sta Raycast.ObjectDraw.Color0.w+6
	sta Raycast.ObjectDraw.Color0.w+7
	sta Raycast.ObjectDraw.Color0.w+8
	sta Raycast.ObjectDraw.Color0.w+9
	sta Raycast.ObjectDraw.Color0.w+10
	sta Raycast.ObjectDraw.Color0.w+11
	sta Raycast.ObjectDraw.Color0.w+12
	sta Raycast.ObjectDraw.Color0.w+13
	sta Raycast.ObjectDraw.Color0.w+14
	sta Raycast.ObjectDraw.Color0.w+15
	sta Raycast.ObjectDraw.Color0.w+16
	sta Raycast.ObjectDraw.Color0.w+17
	sta Raycast.ObjectDraw.Color0.w+18
	sta Raycast.ObjectDraw.Color0.w+19
	sta Raycast.ObjectDraw.Color0.w+20
	sta Raycast.ObjectDraw.Color0.w+21
	sta Raycast.ObjectDraw.Color0.w+22
	sta Raycast.ObjectDraw.Color0.w+23
	sta Raycast.ObjectDraw.Color0.w+24
	sta Raycast.ObjectDraw.Color0.w+25
	sta Raycast.ObjectDraw.Color0.w+26
	sta Raycast.ObjectDraw.Color0.w+27
	sta Raycast.ObjectDraw.Color0.w+28
	sta Raycast.ObjectDraw.Color0.w+29
	sta Raycast.ObjectDraw.Color0.w+30
	sta Raycast.ObjectDraw.Color0.w+31
	sta Raycast.ObjectDraw.Color0.w+32
	sta Raycast.ObjectDraw.Color0.w+33
	sta Raycast.ObjectDraw.Color0.w+34
	sta Raycast.ObjectDraw.Color0.w+35
	sta Raycast.ObjectDraw.Color0.w+36
	sta Raycast.ObjectDraw.Color0.w+37
	sta Raycast.ObjectDraw.Color0.w+38
	sta Raycast.ObjectDraw.Color0.w+39
	sta Raycast.ObjectDraw.Color0.w+40
	sta Raycast.ObjectDraw.Color0.w+41
	sta Raycast.ObjectDraw.Color0.w+42
	sta Raycast.ObjectDraw.Color0.w+43
	sta Raycast.ObjectDraw.Color0.w+44
	rts
	